"""
Dev Agent — core logic.

Receives the QA Agent's failing test case, calls the LLM to generate a
minimal fix suggestion, posts it as a GitHub Issue comment, and publishes
a fix_suggested event so the Notifier Agent can alert the team via Slack.

Entry point: handle()
"""

import base64
import logging

import httpx
import redis.asyncio as redis

from agents.dev import prompts
from core.config import get_github_config
from core.events import publish
from core.llm import complete
from core.models import CrashReport, QAResult
from core.state import write_status
from integrations import github

logger = logging.getLogger(__name__)

_MAX_FILE_CHARS = 4_000


async def handle(
    qa_result: QAResult,
    crash_report: CrashReport,
    redis_client: redis.Redis,
) -> None:
    """
    Generate a fix suggestion and post it to the GitHub Issue.

    Steps:
      1. Fetch relevant source files from GitHub.
      2. Call the LLM to suggest a minimal code fix.
      3. Post the fix suggestion as a comment on the GitHub Issue.
      4. Publish fix_suggested → Notifier Agent sends Slack message.

    Args:
        qa_result:    QAResult from the QA Agent (contains the failing test case).
        crash_report: CrashReport from the Crash Handler Agent.
        redis_client: Async Redis client.
    """
    gh_config = get_github_config()
    incident_id = crash_report.incident_id

    logger.info("dev agent started", extra={"incident_id": incident_id})

    # Step 1 — Fetch source files from GitHub API.
    source_files = await _fetch_source_files(
        repo=gh_config.target_repo,
        paths=qa_result.relevant_files,
        token=gh_config.token,
    )
    logger.debug("source files fetched", extra={"incident_id": incident_id, "files": list(source_files.keys())})

    # Step 2 — LLM generates a fix suggestion.
    suggestion_prompt = prompts.build_suggestion(
        error_type=crash_report.error_type,
        error_message=crash_report.error_message,
        summary=crash_report.summary,
        test_file_path=qa_result.test_case.file_path,
        test_name=qa_result.test_case.test_name,
        test_content=qa_result.test_case.content,
        source_files=source_files,
    )
    fix_suggestion = await complete(agent="dev", prompt=suggestion_prompt)
    logger.debug("llm fix suggestion received", extra={"incident_id": incident_id})

    # Step 3 — Post the fix suggestion as a GitHub Issue comment.
    issue_comment = (
        f"**Suggested fix** for `{crash_report.error_type}: {crash_report.error_message}`\n\n"
        f"{fix_suggestion}\n\n"
        f"---\n"
        f"*Generated by Helix for incident `{incident_id}`.*"
    )
    await github.add_issue_comment(
        repo=gh_config.target_repo,
        issue_number=qa_result.ticket_id,
        comment=issue_comment,
        token=gh_config.token,
    )
    logger.info("fix suggestion posted to github issue", extra={"incident_id": incident_id})

    # Step 4 — Publish fix_suggested; Notifier Agent handles Slack.
    await write_status(redis_client, incident_id, "fix_suggested")
    await publish(
        redis_client,
        "fix_suggested",
        incident_id,
        {"incident_id": incident_id, "issue_url": qa_result.ticket_url, "ticket_id": qa_result.ticket_id},
    )

    logger.info("dev agent complete", extra={"incident_id": incident_id})


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _fetch_source_files(repo: str, paths: list[str], token: str | None = None) -> dict[str, str]:
    """Fetch the content of source files from the GitHub contents API."""
    from integrations.github import _api_headers, _GITHUB_API

    result: dict[str, str] = {}
    async with httpx.AsyncClient() as client:
        for path in paths:
            url = f"{_GITHUB_API}/repos/{repo}/contents/{path}"
            try:
                response = await client.get(url, headers=_api_headers(token))
                response.raise_for_status()
                data = response.json()
                content = base64.b64decode(data["content"]).decode("utf-8", errors="replace")
                if len(content) > _MAX_FILE_CHARS:
                    content = content[:_MAX_FILE_CHARS] + "\n... [truncated]"
                result[path] = content
            except Exception as exc:
                logger.warning("could not fetch source file", extra={"path": path, "error": str(exc)})
    return result
